### ISSUE TITLE
OSSDC discussions

### ISSUE THREAD

**Issue by Qbicz** [OSSDC/OSSDC-Hacking-Book#1]
Hi @mslavescu, the link to discussion at https://github.com/OSSDC is broken. It there any other place for discussion if I want to contribute? Is the OSSDC initiave still active?

**Comment by mslavescu** [comment]
Hi @qbicz,
Thank you for your interest in OSSDC!

The link to join OSSDC Slack is http://join.ossdc.org, it may be slow, try again and wait a bit longer, I just tried and it worked.

The initiative is still active, with most activity in DAC18 challenge algorithms, which we plan to integrate in the initial release of OSSDC Smart Camera based on Nvidia TX2, FPGA PYNQ with Xilinx Zynq 7020 and Lattice Embeded Vision dual camera FPGA kit.

**Comment by Qbicz** [comment]
Thank you for the brief introduction and pointing me in right direction!

Could you update the description of OSSDC? It says the discussion is at http://ossdc.org/join

**Comment by mslavescu** [comment]
Fixed, thanks!
